### ISSUE TITLE
Calendar: ICS Import not working, exception on server

### ISSUE THREAD

**Issue by silicht** [Intermesh/groupoffice#1002]
There is an exception on the server when you try to import an ICS file into a calendar:

## Debug.log

```
[2023-05-29 13:28:00][cron.php][log][GO\Base\Session:407] Session writing closed
[2023-05-29 13:28:08][index.php][log][go\core\jmap\State:114] 'X-CSRF-Token' header or 'CSRFToken' request parameter missing
[2023-05-29 13:28:08][index.php?r=calendar/calendar/importIcs][log][GO\Base\Controller\AbstractController:492] Session writing closed
[2023-05-29 13:28:08][index.php?r=calendar/calendar/importIcs][log][go\core\ErrorHandler:42] ErrorHandler::exceptionHandler() called with ErrorException
[2023-05-29 13:28:08][index.php?r=calendar/calendar/importIcs][error][go\core\ErrorHandler:72] 
        ErrorException in /usr/local/share/groupoffice/go/base/vobject/Iterator.php at line 7: During inheritance of Iterator: Uncaught ErrorException: Return type of GO\Base\Vobject\Iterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/local/share/groupoffice/go/base/vobject/Iterator.php:78
        Stack trace:
        #0 /usr/local/share/groupoffice/go/base/vobject/Iterator.php(7): go\core\ErrorHandler::errorHandler(8192, 'Return type of ...', '/usr/local/shar...', 78)
        #1 /usr/local/share/groupoffice/go/GO.php(549): require('/usr/local/sh
[TestCalendarEntries.ics.txt](https://github.com/Intermesh/groupoffice/files/11592131/TestCalendarEntries.ics.txt)
ar...')
        #2 /usr/local/share/groupoffice/modules/calendar/controller/CalendarController.php(162): GO::autoload('GO\\Base\\Vobject...')
        #3 /usr/local/share/groupoffice/go/base/controller/AbstractController.php(492): GO\Calendar\Controller\CalendarController->actionImportIcs(Array)
        #4 /usr/local/share/groupoffice/go/base/controller/AbstractController.php(390): GO\Base\Controller\AbstractController->callActionMethod('actionimportics', Array)
        #5 /usr/local/share/groupoffice/go/base/Router.php(179): GO\Base\Controller\AbstractController->run('importics', Array)
        #6 /usr/local/share/groupoffice/index.php(127): GO\Base\Router->runController()
        #7 {main}
[2023-05-29 13:28:08][index.php?r=calendar/calendar/importIcs][error][go\core\ErrorHandler:81] #0 [internal function]: go\core\ErrorHandler->shutdown()
[2023-05-29 13:28:08][index.php?r=calendar/calendar/importIcs][error][go\core\ErrorHandler:81] #1 {main}
```

I used a very simple ICS file with two entries that I previously exported from Group Office.

**Comment by mschering** [comment]
Thanks, it was an issue with php 8.1. I have fixed this for the next release.
