### ISSUE TITLE
PDOException in /usr/share/groupoffice/go/core/db/Query.php at line 702: SQLSTATE[HY000]: General error: could not call class constructor

### ISSUE THREAD

**Issue by michalcharvat** [Intermesh/groupoffice#1019]
Anyone else facing same error? Its gone when you clear the cache

```
Firing listener for class GO\Core\Controller\AuthController event head: GO\Customcss\CustomcssModule::head
EXCEPTION: Exception: Can't get not existing property 'aclId' in 'go\core\model\Module' in /usr/share/groupoffice/go/core/orm/Property.php:661
Stack trace:
#0 /usr/share/groupoffice/go/core/orm/Property.php(499): go\core\orm\Property->__get()
#1 /usr/share/groupoffice/go/core/orm/Property.php(157): go\core\orm\Property->trackModifications()
#2 /usr/share/groupoffice/go/core/orm/Entity.php(142): go\core\orm\Property->__construct()
#3 [internal function]: go\core\orm\Entity->__construct()
#4 /usr/share/groupoffice/go/core/db/Query.php(702): PDOStatement->fetchAll()
#5 /usr/share/groupoffice/go/core/model/Module.php(438): go\core\db\Query->all()
#6 /usr/share/groupoffice/go/core/webclient/Extjs3.php(38): go\core\model\Module::getInstalled()
#7 /usr/share/groupoffice/views/Layout.php(59): go\core\webclient\Extjs3->getCSSFile()
#8 /usr/share/groupoffice/views/Extjs3/themes/Paper/Layout.php(4): require('/usr/share/grou...')
#9 /usr/share/groupoffice/controller/AuthController.php(56): require('/usr/share/grou...')
#10 /usr/share/groupoffice/go/base/controller/AbstractController.php(492): GO\Core\Controller\AuthController->actionInit()
#11 /usr/share/groupoffice/go/base/controller/AbstractController.php(390): GO\Base\Controller\AbstractController->callActionMethod()
#12 /usr/share/groupoffice/go/base/Router.php(179): GO\Base\Controller\AbstractController->run()
#13 /usr/share/groupoffice/index.php(127): GO\Base\Router->runController()
#14 {main}

Next PDOException: SQLSTATE[HY000]: General error: could not call class constructor in /usr/share/groupoffice/go/core/db/Query.php:702
Stack trace:
#0 /usr/share/groupoffice/go/core/db/Query.php(702): PDOStatement->fetchAll()
#1 /usr/share/groupoffice/go/core/model/Module.php(438): go\core\db\Query->all()
#2 /usr/share/groupoffice/go/core/webclient/Extjs3.php(38): go\core\model\Module::getInstalled()
#3 /usr/share/groupoffice/views/Layout.php(59): go\core\webclient\Extjs3->getCSSFile()
#4 /usr/share/groupoffice/views/Extjs3/themes/Paper/Layout.php(4): require('/usr/share/grou...')
#5 /usr/share/groupoffice/controller/AuthController.php(56): require('/usr/share/grou...')
#6 /usr/share/groupoffice/go/base/controller/AbstractController.php(492): GO\Core\Controller\AuthController->actionInit()
#7 /usr/share/groupoffice/go/base/controller/AbstractController.php(390): GO\Base\Controller\AbstractController->callActionMethod()
#8 /usr/share/groupoffice/go/base/Router.php(179): GO\Base\Controller\AbstractController->run()
#9 /usr/share/groupoffice/index.php(127): GO\Base\Router->runController()
#10 {main}
PDOException in /usr/share/groupoffice/go/core/db/Query.php at line 702: SQLSTATE[HY000]: General error: could not call class constructor
Previous: Can't get not existing property 'aclId' in 'go\core\model\Module'
#0 /usr/share/groupoffice/go/core/db/Query.php(702): PDOStatement->fetchAll()
#1 /usr/share/groupoffice/go/core/model/Module.php(438): go\core\db\Query->all()
#2 /usr/share/groupoffice/go/core/webclient/Extjs3.php(38): go\core\model\Module::getInstalled()
#3 /usr/share/groupoffice/views/Layout.php(59): go\core\webclient\Extjs3->getCSSFile()
#4 /usr/share/groupoffice/views/Extjs3/themes/Paper/Layout.php(4): require('/usr/share/grou...')
#5 /usr/share/groupoffice/controller/AuthController.php(56): require('/usr/share/grou...')
#6 /usr/share/groupoffice/go/base/controller/AbstractController.php(492): GO\Core\Controller\AuthController->actionInit()
#7 /usr/share/groupoffice/go/base/controller/AbstractController.php(390): GO\Base\Controller\AbstractController->callActionMethod()
#8 /usr/share/groupoffice/go/base/Router.php(179): GO\Base\Controller\AbstractController->run()
#9 /usr/share/groupoffice/index.php(127): GO\Base\Router->runController()
#10 {main}
```

**Comment by mschering** [comment]
no, but It must have something todo with a 6.6 version running on the same system. the aclId column was removed in 6.7.
