### ISSUE TITLE
GO v6.8.5 Newsletter Subscription: Confirmation mail is not sent

### ISSUE THREAD

**Issue by creissig** [Intermesh/groupoffice#1051]
We use the api to make the newsletter subscription. The new contact (as entered in the website) is shown in the addressbook and is awaiting the confirmation. But the confirmation e-mail os not sent: The log shows:

[2023-09-15 21:35:39][JMAP Contact/set][log][go\core\orm\EntityType:524] Pushing 2 JMAP sync changes
[2023-09-15 21:35:39][JMAP Contact/query][log][go\core\jmap\Router:88] Method Contact/query,  ID: clientCallId-1
[2023-09-15 21:35:39][JMAP Contact/get][log][go\core\jmap\Router:88] Method Contact/get,  ID: clientCallId-2
[2023-09-15 21:35:39][JMAP core/Notify/mail][log][go\core\jmap\Router:88] Method core/Notify/mail,  ID: clientCallId-1
[2023-09-15 21:35:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:72] InvalidArgumentException in /usr/share/groupoffice/go/core/mail/Message.php at line 238: Address must be a string or \go\core\mail\Addr>
[2023-09-15 21:35:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #0 /usr/share/groupoffice/go/core/mail/Message.php(253): go\core\mail\Message->normalizeRecipients()
[2023-09-15 21:35:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #1 /usr/share/groupoffice/go/core/controller/Notify.php(19): go\core\mail\Message->setTo()
[2023-09-15 21:35:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #2 [internal function]: go\core\controller\Notify->mail()
[2023-09-15 21:35:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #3 /usr/share/groupoffice/go/core/jmap/Router.php(224): call_user_func()
[2023-09-15 21:35:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #4 /usr/share/groupoffice/go/core/jmap/Router.php(94): go\core\jmap\Router->callAction()
[2023-09-15 21:35:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #5 /usr/share/groupoffice/go/core/jmap/Router.php(63): go\core\jmap\Router->callMethod()
[2023-09-15 21:35:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #6 /usr/share/groupoffice/api/jmap.php(17): go\core\jmap\Router->run()
[2023-09-15 21:35:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #7 {main}
[2023-09-15 21:35:39][JMAP core/Notify/mail][error][go\core\jmap\Response:57]

Array
        (
            [message] => Address must be a string or \go\core\mail\Address
            [type] => invalidArgumentException
            [debugMessage] => InvalidArgumentException in /usr/share/groupoffice/go/core/mail/Message.php at line 238: Address must be a string or \go\core\mail\Address
            [trace] => Array
                (
                    [0] => #0 /usr/share/groupoffice/go/core/mail/Message.php(253): go\core\mail\Message->normalizeRecipients()
                    [1] => #1 /usr/share/groupoffice/go/core/controller/Notify.php(19): go\core\mail\Message->setTo()
                    [2] => #2 [internal function]: go\core\controller\Notify->mail()
                    [3] => #3 /usr/share/groupoffice/go/core/jmap/Router.php(224): call_user_func()
                    [4] => #4 /usr/share/groupoffice/go/core/jmap/Router.php(94): go\core\jmap\Router->callAction()
                    [5] => #5 /usr/share/groupoffice/go/core/jmap/Router.php(63): go\core\jmap\Router->callMethod()
                    [6] => #6 /usr/share/groupoffice/api/jmap.php(17): go\core\jmap\Router->run()
                    [7] => #7 {main}
                )
---

Thanks for advice.

**Comment by mschering** [comment]
Is this something custom made? What is sent in the "to" param?

**Comment by mschering** [comment]
Can you try this commit:

https://github.com/Intermesh/groupoffice/commit/c0b941e9c4337c8a2ea77257bae038fcf1a33230

**Comment by creissig** [comment]
After applying the commit I've got the following error:

[2023-09-18 13:39:38][JMAP Contact/query][log][go\core\jmap\Router:88] Method Contact/query,  ID: clientCallId-1
[2023-09-18 13:39:38][JMAP Contact/get][log][go\core\jmap\Router:88] Method Contact/get,  ID: clientCallId-2
[2023-09-18 13:39:39][JMAP core/Notify/mail][log][go\core\jmap\Router:88] Method core/Notify/mail,  ID: clientCallId-1
[2023-09-18 13:39:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:72] ErrorException in /usr/share/groupoffice/go/core/controller/Notify.php at line 20: foreach() argument must be of type array|object,>
[2023-09-18 13:39:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #0 /usr/share/groupoffice/go/core/controller/Notify.php(20): go\core\ErrorHandler::errorHandler()
[2023-09-18 13:39:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #1 [internal function]: go\core\controller\Notify->mail()
[2023-09-18 13:39:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #2 /usr/share/groupoffice/go/core/jmap/Router.php(224): call_user_func()
[2023-09-18 13:39:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #3 /usr/share/groupoffice/go/core/jmap/Router.php(94): go\core\jmap\Router->callAction()
[2023-09-18 13:39:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #4 /usr/share/groupoffice/go/core/jmap/Router.php(63): go\core\jmap\Router->callMethod()
[2023-09-18 13:39:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #5 /usr/share/groupoffice/api/jmap.php(17): go\core\jmap\Router->run()
[2023-09-18 13:39:39][JMAP core/Notify/mail][error][go\core\ErrorHandler:81] #6 {main}
[2023-09-18 13:39:39][JMAP core/Notify/mail][error][go\core\jmap\Response:57]
        Array
        (
            [message] => foreach() argument must be of type array|object, string given
            [type] => errorException
            [debugMessage] => ErrorException in /usr/share/groupoffice/go/core/controller/Notify.php at line 20: foreach() argument must be of type array|object, string given
            [trace] => Array
                (
                    [0] => #0 /usr/share/groupoffice/go/core/controller/Notify.php(20): go\core\ErrorHandler::errorHandler()
                    [1] => #1 [internal function]: go\core\controller\Notify->mail()
                    [2] => #2 /usr/share/groupoffice/go/core/jmap/Router.php(224): call_user_func()
                    [3] => #3 /usr/share/groupoffice/go/core/jmap/Router.php(94): go\core\jmap\Router->callAction()
                    [4] => #4 /usr/share/groupoffice/go/core/jmap/Router.php(63): go\core\jmap\Router->callMethod()
                    [5] => #5 /usr/share/groupoffice/api/jmap.php(17): go\core\jmap\Router->run()
                    [6] => #6 {main}
                )

        )

**Comment by creissig** [comment]
> Is this something custom made? What is sent in the "to" param?

We use the example scripts for subscribing a new newsletter receiver.

**Comment by mschering** [comment]
Will be fixed in the new release today.
