### ISSUE TITLE
6.6.176 Accessing Ticket crashs with ErrorException Trying to get property 'name' of non-object

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#1059]
Hi,

I somehow "crashed" one ticket. The error occurs when accessing one ticket, then the error is the following

[2023-11-03 17:43:39][index.php?r=tickets/ticket/display][log][GO\Base\Router:179]
        EXCEPTION: ErrorException: Trying to get property 'name' of non-object in /usr/share/groupoffice/modules/tickets/controller/TicketController.php:471
        Stack trace:
        #0 /usr/share/groupoffice/modules/tickets/controller/TicketController.php(471): go\core\ErrorHandler::errorHandler()
        #1 /usr/share/groupoffice/modules/tickets/controller/TicketController.php(381): GO\Tickets\Controller\TicketController->_loadMessages()
        #2 /usr/share/groupoffice/go/base/controller/AbstractModelController.php(466): GO\Tickets\Controller\TicketController->afterDisplay()
        #3 /usr/share/groupoffice/modules/professional/controller/AbstractModelController.php(46): GO\Base\Controller\AbstractModelController->actionDisplay()
        #4 /usr/share/groupoffice/go/base/controller/AbstractController.php(390): GO\Professional\Controller\AbstractModelController->callActionMethod()
        #5 /usr/share/groupoffice/go/base/Router.php(179): GO\Base\Controller\AbstractController->run()
        #6 /usr/share/groupoffice/index.php(124): GO\Base\Router->runController()
        #7 {main}
[2023-11-03 17:43:39][index.php?r=tickets/ticket/display][error][go\core\ErrorHandler:72] ErrorException in /usr/share/groupoffice/modules/tickets/controller/TicketController.php at line 471: Trying to get property 'name' of non-object
[2023-11-03 17:43:39][index.php?r=tickets/ticket/display][error][go\core\ErrorHandler:81] #0 /usr/share/groupoffice/modules/tickets/controller/TicketController.php(471): go\core\ErrorHandler::errorHandler()
[2023-11-03 17:43:39][index.php?r=tickets/ticket/display][error][go\core\ErrorHandler:81] #1 /usr/share/groupoffice/modules/tickets/controller/TicketController.php(381): GO\Tickets\Controller\TicketController->_loadMessages()
[2023-11-03 17:43:39][index.php?r=tickets/ticket/display][error][go\core\ErrorHandler:81] #2 /usr/share/groupoffice/go/base/controller/AbstractModelController.php(466): GO\Tickets\Controller\TicketController->afterDisplay()
[2023-11-03 17:43:39][index.php?r=tickets/ticket/display][error][go\core\ErrorHandler:81] #3 /usr/share/groupoffice/modules/professional/controller/AbstractModelController.php(46): GO\Base\Controller\AbstractModelController->actionDisplay()
[2023-11-03 17:43:39][index.php?r=tickets/ticket/display][error][go\core\ErrorHandler:81] #4 /usr/share/groupoffice/go/base/controller/AbstractController.php(390): GO\Professional\Controller\AbstractModelController->callActionMethod()
[2023-11-03 17:43:39][index.php?r=tickets/ticket/display][error][go\core\ErrorHandler:81] #5 /usr/share/groupoffice/go/base/Router.php(179): GO\Base\Controller\AbstractController->run()
[2023-11-03 17:43:39][index.php?r=tickets/ticket/display][error][go\core\ErrorHandler:81] #6 /usr/share/groupoffice/index.php(124): GO\Base\Router->runController()
[2023-11-03 17:43:39][index.php?r=tickets/ticket/display][error][go\core\ErrorHandler:81] #7 {main}

![image](https://github.com/Intermesh/groupoffice/assets/2633051/8f0ced61-df22-4de8-9d57-d974bae902ec)

The ticket itself is not shown. All the other tickets are fine.
Any ideas?

**Comment by mschering** [comment]
Will be fixed in the next releases of 6.6+

**Comment by thomasgg23** [comment]
6.6.178 fixed the problem. Thanks.
