### ISSUE TITLE
6.8.34 calendar permissions

### ISSUE THREAD

**Issue by Nachtlichtermeer** [Intermesh/groupoffice#1116]
Default all users (group internal) have write-permissions to other calendars.
Thereby it is possible to rename that calendars.
If i change the permission to read i can accept an appointment of another internal user in the GUI
but not through thunderbird.

Installation is native with apache and downloaded tarball because of a bug with ldap in docker.

debug-log:
```
[2024-02-15 12:36:29][CalDAV PUT][log][Sabre\DAVACL\AbstractPrincipalCollection:114] getPrincipalByPath(principals/test@foo.de)
[2024-02-15 12:36:29][CalDAV PUT][log][Sabre\DAV\Tree:83] c:getCalendarsForUser(principals/test@foo.de)
[2024-02-15 12:36:29][CalDAV PUT][log][Sabre\DAV\Tree:83] c:getCalendarObject(4,6088560b-64b8-5322-889c-01fa430c27d5-52)
[2024-02-15 12:36:29][CalDAV PUT][log][Sabre\DAV\Tree:83] Found event 6088560b-64b8-5322-889c-01fa430c27d5-52
[2024-02-15 12:36:29][CalDAV PUT][log][Sabre\CalDAV\Schedule\Plugin:538] updateCalendarObject(4,6088560b-64b8-5322-889c-01fa430c27d5-52,[data])
[2024-02-15 12:36:29][CalDAV PUT][log][Sabre\CalDAV\Schedule\Plugin:538] item is an event
[2024-02-15 12:36:29][CalDAV PUT][log][Sabre\CalDAV\Schedule\Plugin:538] Object is a sinlge VEVENT object
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:70] Sabre\DAV\Exception\Forbidden in /var/www/foo.foo.de/htdocs/modules/caldav/CalendarsBackend.php at line 759: 
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #0 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/CalendarObject.php(103): GO\Caldav\CalendarsBackend->updateCalendarObject()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #1 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(538): Sabre\CalDAV\CalendarObject->put()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #2 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\CalDAV\Schedule\Plugin->scheduleLocalDelivery()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #3 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(350): Sabre\DAV\Server->emit()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #4 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(626): Sabre\CalDAV\Schedule\Plugin->deliver()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #5 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(337): Sabre\CalDAV\Schedule\Plugin->processICalendarChange()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #6 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\CalDAV\Schedule\Plugin->calendarObjectChange()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #7 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Plugin.php(897): Sabre\DAV\Server->emit()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #8 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Plugin.php(739): Sabre\CalDAV\Plugin->validateICalendar()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #9 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\CalDAV\Plugin->beforeWriteContent()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #10 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/Server.php(1133): Sabre\DAV\Server->emit()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #11 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/CorePlugin.php(492): Sabre\DAV\Server->updateFile()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #12 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpPut()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #13 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server->emit()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #14 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #15 /var/www/foo.foo.de/htdocs/modules/caldav/calendar.php(111): Sabre\DAV\Server->start()
[2024-02-15 12:36:29][CalDAV PUT][error][go\core\ErrorHandler:79] #16 {main}
[2024-02-15 12:36:29][CalDAV PUT][log][go\core\orm\EntityType:537] Pushing 1 JMAP sync changes
```

apachelogs:
```
==> ../logs/error.log <==
[Thu Feb 15 12:43:02.179142 2024] [php:notice] [pid 3110240] [client foo:46308] Sabre\\DAV\\Exception\\Forbidden in /var/www/foo.foo.de/htdocs/modules/caldav/CalendarsBackend.php at line 759: 

==> ../logs/access.log <==
foo - foo [15/Feb/2024:12:43:02 +0100] "PUT /caldav/calendars/foo%40foo.de/foo-foo-3/6088560b-64b8-5322-889c-01fa430c27d5-53 HTTP/1.1" 403 2797 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.6.0"
```

**Comment by mschering** [comment]
Hmm, If you have read only permissions you should not be able to accept an event. So It looks like caldav is right here.

**Comment by Nachtlichtermeer** [comment]
That's ok in my option. Is it possible to forbid to rename a calendar with granted write-permissions?

**Comment by Nachtlichtermeer** [comment]
As idea: maybe it is meaningful to allow renaming a calendar only with manager-permissions

**Comment by mschering** [comment]
Yes, this is actually how it works already on the address book, tasklist and notes module so I changed this to be the same.

**Comment by Nachtlichtermeer** [comment]
thanks!

**Comment by Nachtlichtermeer** [comment]
With version 6.8.35 i only can see calendars for which i have manager permissions.
Renaming a calendar with only write permission is unpossible know
