### ISSUE TITLE
6.8.34 undefined method addReplyTo

### ISSUE THREAD

**Issue by Nachtlichtermeer** [Intermesh/groupoffice#1117]
When i sync my calendar with thunderbird and accept an appointment, no mail is sending out:

```
[2024-02-15 12:45:39][CalDAV PUT][error][GO\Caldav\Schedule\IMipPlugin:62] Error sending CalDAV IMip mail to test.test@foo.de,Test
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:70] Error in /var/www/foo.foo.de/htdocs/modules/caldav/schedule/IMipPlugin.php at line 46: Call to undefined method GO\Base\Mail\Message::addReplyTo()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #0 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/IMipPlugin.php(133): GO\Caldav\Schedule\IMipPlugin->mail()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #1 /var/www/foo.foo.de/htdocs/modules/caldav/schedule/IMipPlugin.php(20): Sabre\CalDAV\Schedule\IMipPlugin->schedule()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #2 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): GO\Caldav\Schedule\IMipPlugin->schedule()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #3 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(350): Sabre\DAV\Server->emit()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #4 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(626): Sabre\CalDAV\Schedule\Plugin->deliver()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #5 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(337): Sabre\CalDAV\Schedule\Plugin->processICalendarChange()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #6 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\CalDAV\Schedule\Plugin->calendarObjectChange()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #7 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Plugin.php(897): Sabre\DAV\Server->emit()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #8 /var/www/foo.intecfoosoft.de/htdocs/vendor/sabre/dav/lib/CalDAV/Plugin.php(739): Sabre\CalDAV\Plugin->validateICalendar()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #9 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\CalDAV\Plugin->beforeWriteContent()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #10 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/Server.php(1133): Sabre\DAV\Server->emit()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #11 /var/www/foo.intefoocsoft.de/htdocs/vendor/sabre/dav/lib/DAV/CorePlugin.php(492): Sabre\DAV\Server->updateFile()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #12 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpPut()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #13 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server->emit()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #14 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #15 /var/www/foo.foo.de/htdocs/modules/caldav/calendar.php(111): Sabre\DAV\Server->start()
[2024-02-15 12:45:39][CalDAV PUT][error][go\core\ErrorHandler:79] #16 {main}
```

Installation is native with apache and downloaded tarball because of a bug with ldap in docker.

**Comment by mschering** [comment]
This one will be fixed in the next release.

**Comment by Nachtlichtermeer** [comment]
Tested with version 6.8.35:

```
[2024-02-20 10:14:26][CalDAV PUT][error][GO\Caldav\Schedule\IMipPlugin:62] Error sending CalDAV IMip mail to test.test@foo.de,Test
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:70] PHPMailer\PHPMailer\Exception in /var/www/foo.foo.de/htdocs/vendor/phpmailer/phpmailer/src/PHPMailer.php at line 1101: Invalid address:  (to): Test
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #0 /var/www/foo.foo.de/htdocs/vendor/phpmailer/phpmailer/src/PHPMailer.php(1021): PHPMailer\PHPMailer\PHPMailer->addOrEnqueueAnAddress()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #1 /var/www/foo.foo.de/htdocs/go/core/mail/Mailer.php(292): PHPMailer\PHPMailer\PHPMailer->addAddress()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #2 /var/www/foo.foo.de/htdocs/go/core/mail/Mailer.php(98): go\core\mail\Mailer->applyMessage()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #3 /var/www/foo.foo.de/htdocs/go/core/mail/Mailer.php(127): go\core\mail\Mailer->prepareMessage()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #4 /var/www/foo.foo.de/htdocs/go/base/mail/Mailer.php(68): go\core\mail\Mailer->send()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #5 /var/www/foo.foo.de/htdocs/modules/caldav/schedule/IMipPlugin.php(60): GO\Base\Mail\Mailer->send()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #6 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/IMipPlugin.php(133): GO\Caldav\Schedule\IMipPlugin->mail()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #7 /var/www/foo.foo.de/htdocs/modules/caldav/schedule/IMipPlugin.php(20): Sabre\CalDAV\Schedule\IMipPlugin->schedule()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #8 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): GO\Caldav\Schedule\IMipPlugin->schedule()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #9 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(350): Sabre\DAV\Server->emit()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #10 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(626): Sabre\CalDAV\Schedule\Plugin->deliver()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #11 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Schedule/Plugin.php(337): Sabre\CalDAV\Schedule\Plugin->processICalendarChange()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #12 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\CalDAV\Schedule\Plugin->calendarObjectChange()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #13 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Plugin.php(897): Sabre\DAV\Server->emit()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #14 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/CalDAV/Plugin.php(739): Sabre\CalDAV\Plugin->validateICalendar()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #15 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\CalDAV\Plugin->beforeWriteContent()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #16 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/Server.php(1133): Sabre\DAV\Server->emit()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #17 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/CorePlugin.php(492): Sabre\DAV\Server->updateFile()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #18 /var/www/foo.foo.de/htdocs/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpPut()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #19 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server->emit()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #20 /var/www/foo.foo.de/htdocs/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #21 /var/www/foo.foo.de/htdocs/modules/caldav/calendar.php(111): Sabre\DAV\Server->start()
[2024-02-20 10:14:26][CalDAV PUT][error][go\core\ErrorHandler:79] #22 {main}
```

now i get another error and mail isn't sending, too

That happens when i accept an appointment through thunderbird.

**Comment by mschering** [comment]
Hmm, that's odd. Any idea why your client sends "test" as an email address?

**Comment by Nachtlichtermeer** [comment]
i've cleared my addressbook in tb: same problem
i've tested with another user: same problem

nothing in logs of our SMTP-Server

i think the problem is, that the mail is send to 'test.test@foo.de,Test' instead of 'test.test@foo.de' which is malformed for IMipPlugin

**Comment by Nachtlichtermeer** [comment]
works with 6.8.36, thanks!
