### ISSUE TITLE
An error occurs when select checkbox "Request read confirmation"

### ISSUE THREAD

**Issue by der-HANS** [Intermesh/groupoffice#1170]
An error occurs when writing a new letter, if you select checkbox "Request read confirmation".
Version: 6.8.61

Log:
```
[2024-08-13 01:31:54][index.php?r=email/message/send][log][GO\Base\Router:179]
        EXCEPTION: PHPMailer\PHPMailer\Exception: Invalid header name or value in /var/www/localhost/htdocs/mail/vendor/phpmailer/phpmailer/src/PHPMailer.php:4358
        Stack trace:
        #0 /var/www/localhost/htdocs/mail/go/core/mail/Mailer.php(339): PHPMailer\PHPMailer\PHPMailer->addCustomHeader()
        #1 /var/www/localhost/htdocs/mail/go/core/mail/Mailer.php(99): go\core\mail\Mailer->applyMessage()
        #2 /var/www/localhost/htdocs/mail/go/core/mail/Mailer.php(128): go\core\mail\Mailer->prepareMessage()
        #3 /var/www/localhost/htdocs/mail/go/base/mail/Mailer.php(67): go\core\mail\Mailer->send()
        #4 /var/www/localhost/htdocs/mail/modules/email/controller/MessageController.php(619): GO\Base\Mail\Mailer->send()
        #5 /var/www/localhost/htdocs/mail/go/base/controller/AbstractController.php(486): GO\Email\Controller\MessageController->actionSend()
        #6 /var/www/localhost/htdocs/mail/go/base/controller/AbstractController.php(383): GO\Base\Controller\AbstractController->callActionMethod()
        #7 /var/www/localhost/htdocs/mail/go/base/Router.php(179): GO\Base\Controller\AbstractController->run()
        #8 /var/www/localhost/htdocs/mail/index.php(130): GO\Base\Router->runController()
        #9 {main}
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:70] PHPMailer\PHPMailer\Exception in /var/www/localhost/htdocs/mail/vendor/phpmailer/phpmailer/src/PHPMaile
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:79] #0 /var/www/localhost/htdocs/mail/go/core/mail/Mailer.php(339): PHPMailer\PHPMailer\PHPMailer->addCusto
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:79] #1 /var/www/localhost/htdocs/mail/go/core/mail/Mailer.php(99): go\core\mail\Mailer->applyMessage()
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:79] #2 /var/www/localhost/htdocs/mail/go/core/mail/Mailer.php(128): go\core\mail\Mailer->prepareMessage()
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:79] #3 /var/www/localhost/htdocs/mail/go/base/mail/Mailer.php(67): go\core\mail\Mailer->send()
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:79] #4 /var/www/localhost/htdocs/mail/modules/email/controller/MessageController.php(619): GO\Base\Mail\Mai
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:79] #5 /var/www/localhost/htdocs/mail/go/base/controller/AbstractController.php(486): GO\Email\Controller\M
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:79] #6 /var/www/localhost/htdocs/mail/go/base/controller/AbstractController.php(383): GO\Base\Controller\Ab
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:79] #7 /var/www/localhost/htdocs/mail/go/base/Router.php(179): GO\Base\Controller\AbstractController->run()
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:79] #8 /var/www/localhost/htdocs/mail/index.php(130): GO\Base\Router->runController()
[2024-08-13 01:31:54][index.php?r=email/message/send][error][go\core\ErrorHandler:79] #9 {main}
```
***
Values ​​passed to Disposition-Notification-To:

```
[2024-08-13 01:31:54][index.php?r=email/message/send][log][go\core\mail\Mailer:339] ---------------
[2024-08-13 01:31:54][index.php?r=email/message/send][log][go\core\mail\Mailer:339] Disposition-Notification-To
[2024-08-13 01:31:54][index.php?r=email/message/send][log][go\core\mail\Mailer:339]
        =?utf-8?B?0KHQtdGA0LPQtdC5INCS0LDRgdC40LvRjNC10LLQuNGHINCT0LXQudC90YA=?=
         =?utf-8?B?0LjRhQ==?= <hans@pnisurov.ru>
[2024-08-13 01:31:54][index.php?r=email/message/send][log][go\core\mail\Mailer:339] ---------------
```

***
The error occurs at this location (in the comments temporary stub):
 /var/www/localhost/htdocs/mail/go/core/mail/Mailer.php
```
                $readReceiptTo = $message->getReadReceiptTo();
                if(count($readReceiptTo)) {
                        $headerValue = [];
                        foreach ($readReceiptTo as $a) {
                               $headerValue[] = $this->mail->addrFormat([$a->getEmail(), trim($a->getName())]);
//                            $headerValue[] = $this->mail->addrFormat([$a->getEmail(), '']);
                        }
                        $this->mail->addCustomHeader("Disposition-Notification-To", implode(", ", $headerValue));
                }
```

**Comment by der-HANS** [comment]
The error still exists in the version: 6.8.109

**Comment by mschering** [comment]
This was fixed some time ago. Sorry for not reporting back earlier.
