### ISSUE TITLE
Installer bug in ValidationTrait.php

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#14]
Not sure what's going on here but we get hit with this error while trying to install

ErrorException in /usr/share/groupoffice/go/core/validate/ValidationTrait.php at line 83: count(): Parameter must be an array or an object that implements Countable ErrorException: count(): Parameter must be an array or an object that implements Countable in /usr/share/groupoffice/go/core/validate/ValidationTrait.php:83 

Stack trace: #0 [internal function]: go\core\ErrorHandler::errorHandler(2, 'count(): Parame...', '/usr/share/grou...', 83, Array) #1 /usr/share/groupoffice/go/core/validate/ValidationTrait.php(83): count(NULL) #2 /usr/share/groupoffice/go/core/validate/ValidationTrait.php(20): go\core\orm\Property->hasValidationErrors() #3 /usr/share/groupoffice/go/core/orm/Property.php(512): go\core\orm\Property->validate() #4 /usr/share/groupoffice/go/core/acl/model/Acl.php(90): go\core\orm\Property->internalSave() #5 /usr/share/groupoffice/go/core/acl/model/AclEntity.php(55): go\core\acl\model\Acl->internalSave() #6 /usr/share/groupoffice/go/core/acl/model/AclEntity.php(44): go\core\acl\model\AclEntity->createAcl() #7 /usr/share/groupoffice/go/core/orm/Entity.php(136): go\core\acl\model\AclEntity->internalSave() #8 /usr/share/groupoffice/go/core/Installer.php(53): go\core\orm\Entity->save() #9 /usr/share/groupoffice/install/install.php(31): go\core\Installer->install(Array, Array) #10 {main} Debug dump: array(0) { }

**Comment by gtech99** [comment]
line 83, changed to:

                if ($key === null && is_array($validationErrors)) {
