### ISSUE TITLE
jmap erroring - causing login to fail

### ISSUE THREAD

**Issue by derekdreery** [Intermesh/groupoffice#182]
When I login I get the following error:

<details><summary>[2018-07-31T15:44:49+00:00] Exception in /usr/local/share/groupoffice/go/core/orm/Property.php at line 271: Can't get not existing property 'googleauthenticator' in 'go\modules\core\users\model\User'</summary>

<pre>
Debug dump: 

Array
(
    [0] => [1ms][go\core\db\Connection:387] SELECT t.loginToken, t.accessToken, t.userId, t.createdAt, t.expiresAt, t.lastActiveAt, t.remoteIpAddress, t.userAgent, t.passedMethods, t.loginToken AS `t.loginToken` 
FROM `core_auth_token` `t`
WHERE `t`.`accessToken` = '5b60506e090e56ef61201e6b32d7d50db0c5819c68730'

LIMIT 0,1
    [1] => [3ms][go\core\db\Connection:387] SELECT id 
FROM `core_module` `t`
WHERE `t`.`name` = 'core' 
AND `t`.`package` = 'core'
    [2] => [3ms][go\core\db\Connection:387] SELECT name, value 
FROM `core_setting` `t`
WHERE `t`.`moduleId` = '1'
    [3] => [4ms][go\core\db\Connection:387] SELECT u.id, u.username, u.displayName, u.avatarId, u.enabled, u.email, u.recoveryEmail, u.recoveryHash, u.recoverySendAt, u.lastLogin, u.createdAt, u.modifiedAt, u.dateFormat, u.timeFormat, u.thousandsSeparator, u.decimalSeparator, u.currency, u.loginCount, u.max_rows_list, u.timezone, u.start_module, u.language, u.theme, u.firstWeekday, u.sort_name, u.mute_sound, u.mute_reminder_sound, u.mute_new_mail_sound, u.show_smilies, u.auto_punctuation, u.listSeparator, u.textSeparator, u.files_folder_id, u.disk_quota, u.disk_usage, u.mail_reminders, u.popup_reminders, u.popup_emails, u.holidayset, u.no_reminders, u.last_password_change, u.force_password_change, u.id AS `u.id`, p.password, p.digest, p.userId AS `p.userId` 
FROM `core_user` `u`
LEFT JOIN `core_auth_password` `p` ON u.id = p.userId
WHERE `u`.`id` = 1

LIMIT 0,1
    [4] => [4ms][go\core\db\Connection:387] SELECT ug.groupId, ug.userId, ug.groupId AS `ug.groupId`, ug.userId AS `ug.userId` 
FROM `core_user_group` `ug`
WHERE `ug`.`userId` = 1
    [5] => [5ms][go\core\db\Connection:387] SELECT g.id, g.name, g.createdBy, g.aclId, g.isUserGroupFor, g.id AS `g.id` 
FROM `core_group` `g`
WHERE `g`.`isUserGroupFor` = 1

LIMIT 0,1
    [6] => [5ms][go\core\db\Connection:387] SELECT ug.groupId, ug.userId, ug.groupId AS `ug.groupId`, ug.userId AS `ug.userId` 
FROM `core_user_group` `ug`
WHERE `ug`.`groupId` = 4
    [7] => [5ms][go\core\db\Connection:387] SELECT MAX(level) 
FROM `core_acl_group` `g`
INNER JOIN `core_user_group` `u` ON g.groupId = u.groupId
WHERE `g`.`aclId` = 4 
AND `u`.`userId` = 1
GROUP BY `g`.`aclId`
    [8] => [5ms][go\core\acl\model\Acl:140] Permission level (4-1) = 50
    [9] => [5ms][go\core\db\Connection:387] SELECT * 
FROM `core_user_group` `t`
WHERE `t`.`groupId` = 1 
AND `t`.`userId` = 1

LIMIT 0,1
    [10] => [5ms][go\core\db\Connection:387] SELECT t.id, t.moduleId, t.sortOrder, t.id AS `t.id` 
FROM `core_auth_method` `t`

ORDER BY `t`.`sortOrder` ASC
    [11] => [6ms][go\core\db\Connection:387] SELECT t.id, t.name, t.package, t.version, t.sort_order, t.admin_menu, t.aclId, t.enabled, t.id AS `t.id` 
FROM `core_module` `t`
    [12] => [11ms][go\core\db\Connection:387] SELECT u.id, u.username, u.displayName, u.avatarId, u.enabled, u.email, u.recoveryEmail, u.recoveryHash, u.recoverySendAt, u.lastLogin, u.createdAt, u.modifiedAt, u.dateFormat, u.timeFormat, u.thousandsSeparator, u.decimalSeparator, u.currency, u.loginCount, u.max_rows_list, u.timezone, u.start_module, u.language, u.theme, u.firstWeekday, u.sort_name, u.mute_sound, u.mute_reminder_sound, u.mute_new_mail_sound, u.show_smilies, u.auto_punctuation, u.listSeparator, u.textSeparator, u.files_folder_id, u.disk_quota, u.disk_usage, u.mail_reminders, u.popup_reminders, u.popup_emails, u.holidayset, u.no_reminders, u.last_password_change, u.force_password_change, u.id AS `u.id`, p.password, p.digest, p.userId AS `p.userId` 
FROM `core_user` `u`
LEFT JOIN `core_auth_password` `p` ON u.id = p.userId
WHERE `u`.`username` = 'admin' 
AND `p`.`password` != 'null'

LIMIT 0,1
    [13] => [11ms][go\core\db\Connection:387] SELECT t.id, t.name, t.package, t.version, t.sort_order, t.admin_menu, t.aclId, t.enabled, t.id AS `t.id` 
FROM `core_module` `t`
    [14] => [12ms][go\core\db\Connection:387] SELECT u.id, u.username, u.displayName, u.avatarId, u.enabled, u.email, u.recoveryEmail, u.recoveryHash, u.recoverySendAt, u.lastLogin, u.createdAt, u.modifiedAt, u.dateFormat, u.timeFormat, u.thousandsSeparator, u.decimalSeparator, u.currency, u.loginCount, u.max_rows_list, u.timezone, u.start_module, u.language, u.theme, u.firstWeekday, u.sort_name, u.mute_sound, u.mute_reminder_sound, u.mute_new_mail_sound, u.show_smilies, u.auto_punctuation, u.listSeparator, u.textSeparator, u.files_folder_id, u.disk_quota, u.disk_usage, u.mail_reminders, u.popup_reminders, u.popup_emails, u.holidayset, u.no_reminders, u.last_password_change, u.force_password_change, u.id AS `u.id`, p.password, p.digest, p.userId AS `p.userId` 
FROM `core_user` `u`
LEFT JOIN `core_auth_password` `p` ON u.id = p.userId
WHERE `u`.`username` = 'admin'

LIMIT 0,1
    [15] => [12ms][go\core\ErrorHandler:62] Exception in /usr/local/share/groupoffice/go/core/orm/Property.php at line 271: Can't get not existing property 'googleauthenticator' in 'go\modules\core\users\model\User'
    [16] => [12ms][go\core\ErrorHandler:64] #0 /usr/local/share/groupoffice/go/modules/community/googleauthenticator/Googleauthenticator.php(40): go\core\orm\Property->__get('googleauthentic...')
    [17] => [12ms][go\core\ErrorHandler:64] #1 /usr/local/share/groupoffice/go/modules/core/users/model/User.php(469): go\modules\community\googleauthenticator\Googleauthenticator::isAvailableFor('admin')
    [18] => [12ms][go\core\ErrorHandler:64] #2 /usr/local/share/groupoffice/go/core/orm/Property.php(265): go\modules\core\users\model\User->getAuthenticationMethods()
    [19] => [12ms][go\core\ErrorHandler:64] #3 /usr/local/share/groupoffice/go/core/data/ModelHelper.php(31): go\core\orm\Property->__get('authenticationM...')
    [20] => [12ms][go\core\ErrorHandler:64] #4 /usr/local/share/groupoffice/go/core/data/Model.php(95): go\core\data\ModelHelper::getValue(Object(go\modules\core\users\model\User), 'authenticationM...')
    [21] => [12ms][go\core\ErrorHandler:64] #5 /usr/local/share/groupoffice/go/core/orm/Property.php(952): go\core\data\Model->toArray(Array)
    [22] => [12ms][go\core\ErrorHandler:64] #6 /usr/local/share/groupoffice/go/core/jmap/State.php(104): go\core\orm\Property->toArray()
    [23] => [12ms][go\core\ErrorHandler:64] #7 /usr/local/share/groupoffice/go/core/jmap/State.php(80): go\core\jmap\State->getSession()
    [24] => [12ms][go\core\ErrorHandler:64] #8 /usr/local/share/groupoffice/jmap.php(16): go\core\jmap\State->outputSession()
    [25] => [12ms][go\core\ErrorHandler:64] #9 {main}
)
</pre>
</details>

**Comment by dehart** [comment]
I've tried to reproduce and it looks like the Google Authenticator module is broken in the latest version. Could you disable it for now until the next release?

**Comment by dehart** [comment]
Tried this already.

- [563ms][go\core\ErrorHandler:62] ErrorException in /var/www/groupoffice-6.3/www/go/core/orm/Property.php at line 733: Undefined index: t"
- "[563ms][go\core\ErrorHandler:64] #0 /var/www/groupoffice-6.3/www/go/core/orm/Property.php(733): go\core\ErrorHandler::errorHandler(8, 'Undefined index...', '/var/www/groupo...', 733, Array)"
- "[563ms][go\core\ErrorHandler:64] #1 /var/www/groupoffice-6.3/www/go/core/orm/Property.php(539): go\core\orm\Property->saveTable(Object(go\core\orm\MappedTable), Array)"
- "[563ms][go\core\ErrorHandler:64] #2 /var/www/groupoffice-6.3/www/go/core/orm/Entity.php(158): go\core\orm\Property->internalSave()"
- "[563ms][go\core\ErrorHandler:64] #3 /var/www/groupoffice-6.3/www/go/core/orm/Entity.php(136): go\core\orm\Entity->internalSave()"
- "[563ms][go\core\ErrorHandler:64] #4 /var/www/groupoffice-6.3/www/go/core/auth/BaseAuthenticator.php(40): go\core\orm\Entity->save()"
- "[563ms][go\core\ErrorHandler:64] #5 /var/www/groupoffice-6.3/www/go/modules/community/googleauthenticator/Module.php(22): go\core\auth\BaseAuthenticator::register()"
- "[563ms][go\core\ErrorHandler:64] #6 /var/www/groupoffice-6.3/www/go/core/module/Base.php(70): go\modules\community\googleauthenticator\Module->afterInstall(Object(go\modules\core\modules\model\Module))"
- "[563ms][go\core\ErrorHandler:64] #7 /var/www/groupoffice-6.3/www/go/modules/core/modules/controller/Module.php(42): go\core\module\Base->install()"
- "[563ms][go\core\ErrorHandler:64] #8 [internal function]: go\modules\core\modules\controller\Module->install(Array)"
- "[563ms][go\core\ErrorHandler:64] #9 /var/www/groupoffice-6.3/www/go/core/jmap/Router.php(149): call_user_func(Array, Array)"
- "[563ms][go\core\ErrorHandler:64] #10 /var/www/groupoffice-6.3/www/go/core/jmap/Router.php(66): go\core\jmap\Router->callAction('Module/install', Array)"

then 

- [142ms][go\core\db\Connection:115] CREATE TABLE `googleauth_secret` (↵`userId` int(11) NOT NULL,↵`secret` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,↵`createdAt` datetime NOT NULL↵) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
- "[145ms][go\core\db\Connection:115] SET FOREIGN_KEY_CHECKS=0;"
- "[145ms][go\core\db\Connection:115] DROP TABLE IF EXISTS `googleauth_secret`"
- "[164ms][go\core\db\Connection:115] SET FOREIGN_KEY_CHECKS=1;"
- "[164ms][go\core\ErrorHandler:62] PDOException in /var/www/groupoffice-6.3/www/go/core/db/Connection.php at line 116: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'googleauth_secret' already exists"
- "[164ms][go\core\ErrorHandler:64] #0 /var/www/groupoffice-6.3/www/go/core/db/Connection.php(116): PDO->query('CREATE TABLE `g...')"
- "[164ms][go\core\ErrorHandler:64] #1 /var/www/groupoffice-6.3/www/go/core/module/Base.php(148): go\core\db\Connection->query('CREATE TABLE `g...')"
- "[164ms][go\core\ErrorHandler:64] #2 /var/www/groupoffice-6.3/www/go/core/module/Base.php(46): go\core\module\Base->installDatabase()"
- "[164ms][go\core\ErrorHandler:64] #3 /var/www/groupoffice-6.3/www/go/modules/core/modules/controller/Module.php(42): go\core\module\Base->install()"
- "[164ms][go\core\ErrorHandler:64] #4 [internal function]: go\modules\core\modules\controller\Module->install(Array)"
- "[164ms][go\core\ErrorHandler:64] #5 /var/www/groupoffice-6.3/www/go/core/jmap/Router.php(149): call_user_func(Array, Array)"
- "[164ms][go\core\ErrorHandler:64] #6 /var/www/groupoffice-6.3/www/go/core/jmap/Router.php(66): go\core\jmap\Router->callAction('Module/install', Array)"
- "[164ms][go\core\ErrorHandler:64] #7 /var/www/groupoffice-6.3/www/jmap.php(14): go\core\jmap\Router->run()"
- "[164ms][go\core\ErrorHandler:64] #8 {main}"

**Comment by derekdreery** [comment]
That worked.

**Comment by dehart** [comment]
Good to hear.
My 'core_auth_method' table was missing its primary key. Not sure why but adding it solved my error during installation.

**Comment by derekdreery** [comment]
I had a brief look at the stack trace, and I think there is probably an invariant in the module database table that's being violated, but that's just a guess.
