### ISSUE TITLE
6.4: dragging a contact to an addressbook error

### ISSUE THREAD

**Issue by dehart** [Intermesh/groupoffice#312]
"TypeError: Cannot read property 'replaceClass' of null
    at eval (eval at setIconClass (http://localhost/groupoffice/www/views/Extjs3/ext/ext-all-debug.js:39861:25), <anonymous>:1:13)
    at sb.setIconClass (http://localhost/groupoffice/www/views/Extjs3/ext/ext-all-debug.js:39861:25)
    at sb.onLoad (http://localhost/groupoffice/www/go/modules/community/addressbook/views/extjs3/ContactDetail.js:173:17)
    at sb.internalLoad (http://localhost/groupoffice/www/views/Extjs3/javascript/go/panels/DetailView.js:107:8)
    at sb.onChanges (http://localhost/groupoffice/www/views/Extjs3/javascript/go/panels/DetailView.js:51:9)
    at EXTUTIL.Event.fire (http://localhost/groupoffice/www/views/Extjs3/ext/ext-all-debug.js:326:34)
    at constructor.fireEvent (http://localhost/groupoffice/www/views/Extjs3/ext/ext-all-debug.js:70:31)
    at http://localhost/groupoffice/www/views/Extjs3/javascript/go/data/EntityStore.js:143:7"

**Comment by dehart** [comment]
It happens when I drag the last contact from the group. and the group is selected.
A contact will be removed from 1 group if I drag it to another.
