### ISSUE TITLE
Project income adding or updating 6.4.3

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#366]
Getting the following error when trying at add or edit Project income

Uncaught TypeError: Cannot read property 'trim' of undefined
    at Object.Ext.decode.Ext.util.JSON.decode (script.php?v= 6.4.3:429)
    at sb.success (script.php?v= 6.4.3:273)
    at Ext.data.Connection.handleResponse (ext-all-debug.js:4658)
    at handleTransactionResponse (ext-base-debug.js:2327)
    at XMLHttpRequest.<anonymous> (ext-base-debug.js:2422)

**Comment by mschering** [comment]
Can't replicate this one. Can you check the server error log for errors?

**Comment by Jonnybt4** [comment]
runController()
[24ms][go\core\ErrorHandler:67] #5 {main}
[2ms][GO\Base\Db\Columns:456] Using \GO\Base\Cache\Disk cache
[5ms][closure:664] [2019-04-16 13:45] INIT GET /index.php?r=projects2/income/create&security_token=dkpzR8gCHXVQTJacMrPn&_dc=1555418741215&project_id=225&id=0&security_token=dkpzR8gCHXVQTJacMrPn
[5ms][GO\Base\Router:125] Controller route r=projects2/income/create
[8ms][GO\Base\Controller\AbstractController:102] setIgnoreAclPermissions(true)
[13ms][GO\Base\Db\ActiveRecord:1277] t.*,emte.id as emteid
[21ms][go\core\ErrorHandler:65] Error in /usr/share/groupoffice/modules/projects2/controller/IncomeController.php at line 124: Call to undefined method go\modules\community\addressbook\model\Contact::getFormattedAddress()
[21ms][go\core\ErrorHandler:67] #0 /usr/share/groupoffice/go/base/controller/AbstractController.php(487): GO\Projects2\Controller\IncomeController->actionCreate(Array)
[21ms][go\core\ErrorHandler:67] #1 /usr/share/groupoffice/go/base/controller/AbstractController.php(396): GO\Base\Controller\AbstractController->callActionMethod('actioncreate', Array)
[21ms][go\core\ErrorHandler:67] #2 /usr/share/groupoffice/go/base/Router.php(182): GO\Base\Controller\AbstractController->run('create', Array)
[21ms][go\core\ErrorHandler:67] #3 /usr/share/groupoffice/index.php(108): GO\Base\Router->runController()
[21ms][go\core\ErrorHandler:67] #4 {main}

**Comment by mschering** [comment]
Fixed in 6.4.6
