### ISSUE TITLE
Document from template 6.4.6

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#381]
Getting this error when trying to create a document from a template

**Console**
Uncaught TypeError: Cannot read property 'trim' of undefined
    at Object.Ext.decode.Ext.util.JSON.decode (script.php?v= 6.4.6:422)
    at GO.documenttemplates.TemplateDocumentDialog.success (script.php?v= 6.4.6:273)
    at Ext.data.Connection.handleResponse (ext-all-debug.js:4658)
    at handleTransactionResponse (ext-base-debug.js:2327)
    at XMLHttpRequest.<anonymous> (ext-base-debug.js:2422)

**Debug** 
[GO\Base\Router:125] Controller route r=documenttemplates/document/create
[11ms][go\core\ErrorHandler:65] Error in /usr/share/groupoffice/modules/documenttemplates/controller/DocumentController.php at line 164: Call to undefined method GO\Projects2\Model\Project::findbyid()
[11ms][go\core\ErrorHandler:67] #0 /usr/share/groupoffice/go/base/controller/AbstractController.php(487): GO\Documenttemplates\Controller\DocumentController->actionCreate(Array)
[11ms][go\core\ErrorHandler:67] #1 /usr/share/groupoffice/go/base/controller/AbstractController.php(396): GO\Base\Controller\AbstractController->callActionMethod('actioncreate', Array)
[11ms][go\core\ErrorHandler:67] #2 /usr/share/groupoffice/go/base/Router.php(182): GO\Base\Controller\AbstractController->run('create', Array)
[11ms][go\core\ErrorHandler:67] #3 /usr/share/groupoffice/index.php(112): GO\Base\Router->runController()
[11ms][go\core\ErrorHandler:67] #4 {main}

**Error log**
[Fri May 03 09:17:50.260329 2019] [:error] [pid 48088] [client ip:port] Error in /usr/share/groupoffice/modules/documenttemplates/controller/DocumentController.php at line 164: Call to undefined method GO\\Projects2\\Model\\Project::findbyid(), referer: https://portal/

**Comment by mschering** [comment]
Will be fixed in the next release.
