### ISSUE TITLE
6.4.7 installation failed

### ISSUE THREAD

**Issue by cvantum** [Intermesh/groupoffice#382]
Hello,

we are running an instance of group-office at our environment with an Debian Stretch-Server and Group-Office repository.

An upgrade from previous version 6.3.72 to 6.4.7 went fine without any problems.

After some tests with dummy-data we tried to reset our instance via:
```
dpkg-reconfigure groupoffice
```
And also deleted all given data in groupoffice-database. But after i followed the installation-routine on the website i hit an error:

```
Exception in /usr/share/groupoffice/go/core/db/Utils.php at line 21: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') ENGINE=InnoDB' at line 4 on query (4) CREATE TABLE `core_auth_password` (\n`userId` int(11) NOT NULL,\n`password` varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n) ENGINE=InnoDB, referer: https://<URL>/groupoffice/install/install.php
```

At the moment it's only possible to get a working instance while downgrade the packages again to 6.3.72, follow the installation-process at the web-site and then doing an upgrade via `apt`.

**Comment by mschering** [comment]
Thanks! Fixed the error.

**Comment by cvantum** [comment]
Your're welcome :+1: thanks a lot.

**Comment by cvantum** [comment]
After package upgrade to `6.4.8` re-installation failed too with an other exeption:
```
Exception in /usr/share/groupoffice/go/core/db/Utils.php at line 21: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes on query (67) ALTER TABLE `core_search` ADD INDEX(`keywords`) at 2019-05-15T05:27:49+00:00
```

This is also caused during installation on web-page via `install.php`

**Comment by mschering** [comment]
Strange, how big is the keywords field in your database? It should be 192 chars to be just under the max size.

**Comment by cvantum** [comment]
This problem is caused while running `install.php` and logged a second error in `/var/log/apache/error.log`

We are running this instance of Group-Office on a Debian Server with stable-Version ( stretch ) 
```
Exception in /usr/share/groupoffice/go/core/db/Utils.php at line 21: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes on query (67) ALTER TABLE `core_search` ADD INDEX(`keywords`), referer: https://<URL>/groupoffice/install/install.php
```

This are the fields of this table;
```
MariaDB [groupoffice]> show columns from core_search;
+--------------+--------------+------+-----+---------+-------+
| Field        | Type         | Null | Key | Default | Extra |
+--------------+--------------+------+-----+---------+-------+
| id           | int(11)      | NO   | PRI | NULL    |       |
| entityId     | int(11)      | NO   | MUL | NULL    |       |
| moduleId     | int(11)      | YES  | MUL | NULL    |       |
| name         | varchar(100) | YES  | MUL | NULL    |       |
| description  | varchar(192) | YES  |     | NULL    |       |
| entityTypeId | int(11)      | NO   | MUL | NULL    |       |
| keywords     | varchar(192) | NO   |     |         |       |
| filter       | varchar(50)  | YES  | MUL | NULL    |       |
| modifiedAt   | datetime     | YES  |     | NULL    |       |
| aclId        | int(11)      | NO   | MUL | NULL    |       |
+--------------+--------------+------+-----+---------+-------+
10 rows in set (0.00 sec)

MariaDB [groupoffice]> 
```

I ran this process with debug-mode and got this additional informations:

```
[15ms][go\core\cache\Disk:132] Flushing cache
[16ms][go\core\cache\None:20] Not using cache. This will be slow!
[5848ms][go\core\ErrorHandler:65] Exception in /usr/share/groupoffice/go/core/db/Utils.php at line 21: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes on query (67) ALTER TABLE `core_search` ADD INDEX(`keywords`)
[5848ms][go\core\ErrorHandler:67] #0 /usr/share/groupoffice/go/core/Installer.php(73): go\core\db\Utils::runSQLFile(Object(go\core\fs\File))
[5848ms][go\core\ErrorHandler:67] #1 /usr/share/groupoffice/install/install.php(64): go\core\Installer->install(Array, Array)
[5848ms][go\core\ErrorHandler:67] #2 {main}
```

Hope it helps and thanks you in advance.

**Comment by mschering** [comment]
Do you use REDUNDANT row format in mysql as default? I noticed this error appears when I try this row format.

**Comment by mschering** [comment]
Anyway, in the next release i've lowered the column length to 190 chars and this should fix your problem.
