### ISSUE TITLE
Error while migrating addressbook from 6.3 to 6.4

### ISSUE THREAD

**Issue by fischli** [Intermesh/groupoffice#474]
Tried to migrate from 6.3.81 to 6.4.61 and got the following exception. Migration process failed and i had to rollback to 6.3

```
Error: Exception in /var/www/GroupOffice/groupoffice/go/core/model/Link.php at line 163: Couldn't create link: array (
  'toId' => 
  array (
    'code' => 11,
    'description' => 'The property must be unique',
  ),
)

#0 /var/www/GroupOffice/groupoffice/go/modules/community/addressbook/install/Migrate63to64.php(556): go\core\model\Link::create(Object(go\modules\community\addressbook\model\Contact), Object(go\modules\community\addressbook\model\Contact), NULL, false)
#1 /var/www/GroupOffice/groupoffice/go/modules/community/addressbook/install/Migrate63to64.php(78): go\modules\community\addressbook\install\Migrate63to64->copyContacts(Object(go\modules\community\addressbook\model\AddressBook))
#2 /var/www/GroupOffice/groupoffice/go/modules/community/addressbook/install/updates.php(13): go\modules\community\addressbook\install\Migrate63to64->run()
#3 [internal function]: go\core\Installer->{closure}()
#4 /var/www/GroupOffice/groupoffice/go/core/Installer.php(507): call_user_func(Object(Closure))
#5 /var/www/GroupOffice/groupoffice/go/core/Installer.php(341): go\core\Installer->upgradeModules()
#6 /var/www/GroupOffice/groupoffice/install/upgrade.php(77): go\core\Installer->upgrade()
#7 {main}
```

**Comment by mschering** [comment]
Can you try to replace:

www/go/modules/community/addressbook/install/Migrate63to64.php with the file from GitHub. I solved this issue.

**Comment by fischli** [comment]
thanks for the quick response! I will try tomorrow and will give you feedback.

**Comment by fischli** [comment]
Works so far - when you take it into account to disable the SaveMailAs module and to enable the Files module. Otherwise ...
```
Error: PDOException in /var/www/GroupOffice/groupoffice/go/base/db/Columns.php at line 78: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'groupoffice.fs_folders' doesn't exist

#0 /var/www/GroupOffice/groupoffice/go/base/db/Columns.php(78): PDO->query('SHOW COLUMNS FR...')
#1 /var/www/GroupOffice/groupoffice/go/base/db/ActiveRecord.php(477): GO\Base\Db\Columns::getColumns(Object(GO\Files\Model\Folder))
#2 /var/www/GroupOffice/groupoffice/go/base/Model.php(130): GO\Base\Db\ActiveRecord->__construct(false, true)
#3 /var/www/GroupOffice/groupoffice/go/modules/community/addressbook/Module.php(93): GO\Base\Model::model()
#4 /var/www/GroupOffice/groupoffice/go/modules/community/addressbook/install/updates.php(69): go\modules\community\addressbook\Module::checkRootFolder()
#5 [internal function]: go\core\Installer->{closure}()
#6 /var/www/GroupOffice/groupoffice/go/core/Installer.php(507): call_user_func(Object(Closure))
#7 /var/www/GroupOffice/groupoffice/go/core/Installer.php(341): go\core\Installer->upgradeModules()
#8 /var/www/GroupOffice/groupoffice/install/upgrade.php(77): go\core\Installer->upgrade()
#9 {main}
```

**Comment by mschering** [comment]
I will fix that upgrade error. But what happens with the savemailas module?

**Comment by fischli** [comment]
Upgrading by gui suggests only to disable this module. I had the option to continue the process and everything went fine. This possibility wasn't offered while using the cli tool. Maybe there is an option to the cli tool? Didn't look deeper into it.
