### ISSUE TITLE
PDOException 'shortDateInList'

### ISSUE THREAD

**Issue by rasos** [Intermesh/groupoffice#536]
We see in the logfiles frequently: 

`[Tue Jan 07 16:50:04.939690 2020] [proxy_fcgi:error] [pid 15174:tid 2898672448] [client 194.208.212.51:37228] AH01071: Got error 'PHP message: PDOException in /usr/share/groupoffice/go/core/db/Statement.php at line 93: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'shortDateInList' at row 1\n', referer: https://fairkom.net/groupoffice/`

it seems that this should be boolean, not integer, see www/go/core/install/updates.php
`
$updates["201810111129"][] = "ALTER TABLE `core_user` ADD `shortDateInList` BOOLEAN NOT NULL DEFAULT TRUE AFTER `dateFormat`;";`

**Comment by rasos** [comment]
The error is thrown when trying to add a new user:

```
[error][go\core\ErrorHandler:65] PDOException in /usr/share/groupoffice/go/core/db/Statement.php at line 93: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'shortDateInList' at row 1
[error][go\core\ErrorHandler:68] #0 /usr/share/groupoffice/go/core/db/Statement.php(93): PDOStatement->execute(NULL)
[error][go\core\ErrorHandler:68] #1 /usr/share/groupoffice/go/core/orm/Property.php(1491): go\core\db\Statement->execute()
[error][go\core\ErrorHandler:68] #2 /usr/share/groupoffice/go/core/orm/Property.php(1025): go\core\orm\Property->saveTable(Object(go\core\orm\MappedTable), Array)
[error][go\core\ErrorHandler:68] #3 /usr/share/groupoffice/go/core/orm/Property.php(984): go\core\orm\Property->saveTables()
[error][go\core\ErrorHandler:68] #4 /usr/share/groupoffice/go/core/orm/Entity.php(265): go\core\orm\Property->internalSave()
[error][go\core\ErrorHandler:68] #5 /usr/share/groupoffice/go/core/jmap/Entity.php(67): go\core\orm\Entity->internalSave()
[error][go\core\ErrorHandler:68] #6 /usr/share/groupoffice/go/core/model/User.php(597): go\core\jmap\Entity->internalSave()
[error][go\core\ErrorHandler:68] #7 /usr/share/groupoffice/go/core/orm/Entity.php(216): go\core\model\User->internalSave()
[error][go\core\ErrorHandler:68] #8 /usr/share/groupoffice/go/core/jmap/EntityController.php(583): go\core\orm\Entity->save()
[error][go\core\ErrorHandler:68] #9 /usr/share/groupoffice/go/core/jmap/EntityController.php(553): go\core\jmap\EntityController->createEntitites(Array, Array)
[error][go\core\ErrorHandler:68] #10 /usr/share/groupoffice/go/core/controller/User.php(92): go\core\jmap\EntityController->defaultSet(Array)
[error][go\core\ErrorHandler:68] #11 [internal function]: go\core\controller\User->set(Array)
[error][go\core\ErrorHandler:68] #12 /usr/share/groupoffice/go/core/jmap/Router.php(201): call_user_func(Array, Array)
[error][go\core\ErrorHandler:68] #13 /usr/share/groupoffice/go/core/jmap/Router.php(92): go\core\jmap\Router->callAction('User/set', Array)
[error][go\core\ErrorHandler:68] #14 /usr/share/groupoffice/go/core/jmap/Router.php(68): go\core\jmap\Router->callMethod(Array)
[error][go\core\ErrorHandler:68] #15 /usr/share/groupoffice/api/jmap.php(14): go\core\jmap\Router->run()
[error][go\core\ErrorHandler:68] #16 {main}
[error][go\core\orm\Property:1535] 
        Failed SQL: INSERT INTO `core_user`  (
        	`username`,
        	`displayName`,
        	`email`,
        	`dateFormat`,
        	`shortDateInList`,
        	`timeFormat`,
        	`currency`,
        	`timezone`,
        	`language`,
        	`firstWeekday`,
        	`recoveryEmail`,
        	`modifiedAt`,
        	`createdAt`,
        	`id`
        )
        VALUES 
        (
        	'first.last@comppny.eu',
        	'First Last',
        	'first.last@comppny.eu',
        	'd.m.Y',
        	'',
        	'H:i',
        	'€',
        	'Europe/Berlin',
        	'de',
        	'1',
        	'first.last@comppny.eu',
        	'2020-01-07 16:38:03',
        	'2020-01-07 16:38:03',
        	NULL
        )
[error][go\core\orm\Property:1536] SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'shortDateInList' at row 1
[error][go\core\orm\Property:1537] 
```

**Comment by mschering** [comment]
Can you check in the database if it's indeed a boolean value?

**Comment by rasos** [comment]
Our GO database (which we use since many years and had many upgrades) shows 

| 8 | shortDateInList | tinyint(1) |   |   | Nein | 1 |

**Comment by mschering** [comment]
I can't explain why this happens. Can you try to run /install/upgrade.php to clear and rebuild the server cached column definitions? If that doesn't help I can only help with access to the server I'm afraid.

**Comment by mschering** [comment]
This happened when the default for shortDateInList was set to false. Will be fixed in the next release.
